const profileform = document.querySelector('#formprofile');
const countryinput = document.getElementById("InputCountry");

const countrylist = [
    "afghanistan",
    "albania",
    "algeria",
    "andorra",
    "angola",
    "anguilla",
    "antigua-and-barbuda",
    "argentina",
    "armenia",
    "aruba",
    "australia",
    "austria",
    "azerbaijan",
    "bahamas",
    "bahrain",
    "bangladesh",
    "barbados",
    "belarus",
    "belgium",
    "belize",
    "benin",
    "bermuda",
    "bhutan",
    "bolivia",
    "bosnia-and-herzegovina",
    "botswana",
    "brazil",
    "british-virgin-islands",
    "brunei",
    "bulgaria",
    "burkina-faso",
    "burundi",
    "cabo-verde",
    "cambodia",
    "cameroon",
    "canada",
    "car",
    "caribbean-netherlands",
    "cayman-islands",
    "chad",
    "channel-islands",
    "chile",
    "china",
    "colombia",
    "comoros",
    "congo",
    "cook-islands",
    "costa-rica",
    "croatia",
    "cuba",
    "cura&ccedil;ao",
    "cyprus",
    "czechia",
    "denmark",
    "diamond-princess",
    "djibouti",
    "dominica",
    "dominican-republic",
    "dprk",
    "drc",
    "ecuador",
    "egypt",
    "el-salvador",
    "equatorial-guinea",
    "eritrea",
    "estonia",
    "eswatini",
    "ethiopia",
    "faeroe-islands",
    "falkland-islands",
    "fiji",
    "finland",
    "france",
    "french-guiana",
    "french-polynesia",
    "gabon",
    "gambia",
    "georgia",
    "germany",
    "ghana",
    "gibraltar",
    "greece",
    "greenland",
    "grenada",
    "guadeloupe",
    "guatemala",
    "guinea",
    "guinea-Bissau",
    "guyana",
    "haiti",
    "honduras",
    "hong-kong",
    "hungary",
    "iceland",
    "india",
    "indonesia",
    "iran",
    "iraq",
    "ireland",
    "isle-of-man",
    "israel",
    "italy",
    "ivory-coast",
    "jamaica",
    "japan",
    "jordan",
    "kazakhstan",
    "kenya",
    "kiribati",
    "kuwait",
    "kyrgyzstan",
    "laos",
    "latvia",
    "lebanon",
    "lesotho",
    "liberia",
    "libya",
    "liechtenstein",
    "lithuania",
    "luxembourg",
    "macao",
    "madagascar",
    "malawi",
    "malaysia",
    "maldives",
    "mali",
    "malta",
    "marshall-islands",
    "martinique",
    "mauritania",
    "mauritius",
    "mayotte",
    "mexico",
    "micronesia",
    "moldova",
    "monaco",
    "mongolia",
    "montenegro",
    "montserrat",
    "morocco",
    "mozambique",
    "ms-zaandam",
    "myanmar",
    "namibia",
    "nauru",
    "nepal",
    "netherlands",
    "new-caledonia",
    "new-zealand",
    "nicaragua",
    "niger",
    "nigeria",
    "niue",
    "north-macedonia",
    "norway",
    "oman",
    "pakistan",
    "palau",
    "palestine",
    "panama",
    "papua-new-guinea",
    "paraguay",
    "peru",
    "philippines",
    "poland",
    "portugal",
    "qatar",
    "r&eacute;union",
    "romania",
    "russia",
    "rwanda",
    "s-korea",
    "saint-helena",
    "saint-kitts-and-nevis",
    "saint-lucia",
    "saint-martin",
    "saint-pierre-miquelon",
    "samoa",
    "san-marino",
    "sao-tome-and-principe",
    "saudi-arabia",
    "senegal",
    "serbia",
    "seychelles",
    "sierra-leone",
    "singapore",
    "sint-maarten",
    "slovakia",
    "slovenia",
    "solomon-islands",
    "somalia",
    "south-africa",
    "south-sudan",
    "spain",
    "sri-lanka",
    "st-barth",
    "st-vincent-grenadines",
    "sudan",
    "suriname",
    "sweden",
    "switzerland",
    "syria",
    "taiwan",
    "tajikistan",
    "tanzania",
    "thailand",
    "timor-leste",
    "togo",
    "tokelau",
    "tonga",
    "trinidad-and-tobago",
    "tunisia",
    "turkey",
    "turks-and-caicos",
    "tuvalu",
    "uae",
    "uganda",
    "uk",
    "ukraine",
    "uruguay",
    "usa",
    "uzbekistan",
    "vanuatu",
    "vatican-city",
    "venezuela",
    "vietnam",
    "wallis-and-futuna",
    "western-sahara",
    "yemen",
    "zambia",
    "zimbabwe"
  ];

const base_url = 'https://covid-193.p.rapidapi.com/statistics?country=';
const options = {
	method: 'GET',
	headers: {
		'X-RapidAPI-Key': '35051c8d47msh6f20781bdb30142p1102ecjsn2327f5781ece',
		'X-RapidAPI-Host': 'covid-193.p.rapidapi.com'
	}
};

function process(data) {

    document.getElementById("active").innerHTML = data.cases.active ?? 0;
    document.getElementById("new").innerHTML = data.cases.new ?? 0;
    document.getElementById("recovered").innerHTML = data.cases.recovered ?? 0;
    document.getElementById("total-cases").innerHTML = data.cases.total ?? 0;
    document.getElementById("total-deaths").innerHTML = data.deaths.total ?? 0;
    document.getElementById("total-tests").innerHTML = data.tests.total ?? 0;

};

profileform.addEventListener("submit", (event) => {
    event.preventDefault();
    userinput = countryinput.value.toLowerCase();

    if(countrylist.includes(userinput)){
        fix_url = base_url + userinput;

        fetch(fix_url,options)
        .then((response) => {
            if (!response.ok) {
                throw new Error(`${response.status} ${response.statusText}`);
            }
            return response.json();
        }).then((data) => {
            process(data.response[0]);
        }).catch((err) => {
            console.log(err);
        });
    } else {
        alert("Invalid Country");
    }

});
