const profileform = document.querySelector('#formprofile');
const countryinput = document.getElementById("InputCountry");

const countrylist = [
    "afghanistan",
    "albania",
    "algeria",
    "andorra",
    "angola",
    "anguilla",
    "antigua-and-Barbuda",
    "argentina",
    "armenia",
    "aruba",
    "australia",
    "austria",
    "azerbaijan",
    "bahamas",
    "bahrain",
    "bangladesh",
    "barbados",
    "belarus",
    "belgium",
    "belize",
    "benin",
    "bermuda",
    "bhutan",
    "bolivia",
    "bosnia-and-Herzegovina",
    "botswana",
    "brazil",
    "british-Virgin-Islands",
    "brunei",
    "bulgaria",
    "burkina-Faso",
    "burundi",
    "cabo-Verde",
    "cambodia",
    "cameroon",
    "canada",
    "cAR",
    "caribbean-Netherlands",
    "cayman-Islands",
    "chad",
    "channel-Islands",
    "chile",
    "china",
    "colombia",
    "comoros",
    "congo",
    "cook-Islands",
    "costa-Rica",
    "croatia",
    "cuba",
    "cura&ccedil;ao",
    "cyprus",
    "czechia",
    "denmark",
    "diamond-Princess",
    "djibouti",
    "dominica",
    "dominican-Republic",
    "dPRK",
    "dRC",
    "ecuador",
    "egypt",
    "el-Salvador",
    "equatorial-Guinea",
    "eritrea",
    "estonia",
    "eswatini",
    "ethiopia",
    "faeroe-Islands",
    "falkland-Islands",
    "fiji",
    "finland",
    "france",
    "french-Guiana",
    "french-Polynesia",
    "gabon",
    "gambia",
    "georgia",
    "germany",
    "ghana",
    "gibraltar",
    "greece",
    "greenland",
    "grenada",
    "guadeloupe",
    "guatemala",
    "guinea",
    "guinea-Bissau",
    "guyana",
    "haiti",
    "honduras",
    "hong-Kong",
    "hungary",
    "iceland",
    "india",
    "indonesia",
    "iran",
    "iraq",
    "ireland",
    "isle-of-Man",
    "israel",
    "italy",
    "ivory-Coast",
    "jamaica",
    "japan",
    "jordan",
    "kazakhstan",
    "kenya",
    "kiribati",
    "kuwait",
    "kyrgyzstan",
    "laos",
    "latvia",
    "lebanon",
    "lesotho",
    "liberia",
    "libya",
    "liechtenstein",
    "lithuania",
    "luxembourg",
    "macao",
    "madagascar",
    "malawi",
    "malaysia",
    "maldives",
    "mali",
    "malta",
    "marshall-Islands",
    "martinique",
    "mauritania",
    "mauritius",
    "mayotte",
    "mexico",
    "micronesia",
    "moldova",
    "monaco",
    "mongolia",
    "montenegro",
    "montserrat",
    "morocco",
    "mozambique",
    "mS-Zaandam",
    "myanmar",
    "namibia",
    "nauru",
    "nepal",
    "netherlands",
    "new-Caledonia",
    "new-Zealand",
    "nicaragua",
    "niger",
    "nigeria",
    "niue",
    "north-Macedonia",
    "norway",
    "oman",
    "pakistan",
    "palau",
    "palestine",
    "panama",
    "papua-New-Guinea",
    "paraguay",
    "peru",
    "philippines",
    "poland",
    "portugal",
    "qatar",
    "r&eacute;union",
    "romania",
    "russia",
    "rwanda",
    "s-Korea",
    "saint-Helena",
    "saint-Kitts-and-Nevis",
    "saint-Lucia",
    "saint-Martin",
    "saint-Pierre-Miquelon",
    "samoa",
    "san-Marino",
    "sao-Tome-and-Principe",
    "saudi-Arabia",
    "senegal",
    "serbia",
    "seychelles",
    "sierra-Leone",
    "singapore",
    "sint-Maarten",
    "slovakia",
    "slovenia",
    "solomon-Islands",
    "somalia",
    "south-Africa",
    "south-Sudan",
    "spain",
    "sri-Lanka",
    "st-Barth",
    "st-Vincent-Grenadines",
    "sudan",
    "suriname",
    "sweden",
    "switzerland",
    "syria",
    "taiwan",
    "tajikistan",
    "tanzania",
    "thailand",
    "timor-Leste",
    "togo",
    "tokelau",
    "tonga",
    "trinidad-and-Tobago",
    "tunisia",
    "turkey",
    "turks-and-Caicos",
    "tuvalu",
    "uAE",
    "uganda",
    "uK",
    "ukraine",
    "uruguay",
    "uSA",
    "uzbekistan",
    "vanuatu",
    "vatican-City",
    "venezuela",
    "vietnam",
    "wallis-and-Futuna",
    "western-Sahara",
    "yemen",
    "zambia",
    "zimbabwe"
  ];

const base_url = 'https://covid-193.p.rapidapi.com/statistics?country=';
const options = {
	method: 'GET',
	headers: {
		'X-RapidAPI-Key': '35051c8d47msh6f20781bdb30142p1102ecjsn2327f5781ece',
		'X-RapidAPI-Host': 'covid-193.p.rapidapi.com'
	}
};

function process(data) {

    document.getElementById("active").innerHTML = data.cases.active ?? 0;
    document.getElementById("new").innerHTML = data.cases.new ?? 0;
    document.getElementById("recovered").innerHTML = data.cases.recovered ?? 0;
    document.getElementById("total-cases").innerHTML = data.cases.total ?? 0;
    document.getElementById("total-deaths").innerHTML = data.deaths.total ?? 0;
    document.getElementById("total-tests").innerHTML = data.tests.total ?? 0;

};

profileform.addEventListener("submit", (event) => {
    event.preventDefault();
    userinput = countryinput.value.toLowerCase();

    if(countrylist.includes(userinput)){
        fix_url = base_url + userinput;

        fetch(fix_url,options)
        .then((response) => {
            if (!response.ok) {
                throw new Error(`${response.status} ${response.statusText}`);
            }
            return response.json();
        }).then((data) => {
            process(data.response[0]);
        }).catch((err) => {
            console.log(err);
        });
    } else {
        alert("Invalid Country");
    }

});
